config/routes.rb
Rails.application.routes.draw do

  get   '/login', :to => 'sessions#new', :as => :login
  get '/auth/:provider/callback', :to => 'sessions#create'
  get '/auth/failure', :to => 'sessions#failure'
  get '/logout', :to => 'sessions#destroy'

devise_for :users

resources :users do
    resources :expenditures
  end

  root 'sessions#new'

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
	belongs_to :user
	validates :provider, :uid, :presence => true
end

app/models/expenditure.rb
class Expenditure < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, styles: { small: "64x64", med: "200x200", large: "400x400" }, :default_url => "/images/:style/missing.png"
	validates :item, :price, :presence => true
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :authorizations
	has_many :expenditures
	validates :name, :email, :presence => true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/expenditures_controller.rb
class ExpendituresController < ApplicationController
	def new
		@expenditure = Expenditure.new
	end

	def create
		@expenditure = Expenditure.create(expenditure_params)

		if @expenditure.save
			redirect_to @expenditure
		else
			render :new
		end
	end

	def index
		@expenditures = Expenditure.all
	end

	def show
		@expenditure = Expenditure.find(params[:id])
	end

	def edit
		@expenditure = Expenditure.find(params[:id])
	end

	def update 
		@expenditure = Expenditure.create(expenditure_params)

		if @expenditure.save
			redirect_to @expenditure
		else
			render :edit
		end
	end

private

	def expenditure_params
		params.require(:expenditure).permit(:item, :price, :image)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	@user = current_user
  end

  def create
  	auth_hash = request.env['omniauth.auth']

  	@authorization = Authorization.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
	if @authorization
	    render :text => "Welcome back #{@authorization.user.name}! You have already signed up."
	else
	    user = User.new :name => auth_hash["user_info"]["name"], :email => auth_hash["user_info"]["email"]
	    user.authorizations.build :provider => auth_hash["provider"], :uid => auth_hash["uid"]
	    user.save
 
  		render :text => auth_hash.inspect
  	end
  end

  def failure
  render :text => "Sorry, but you didn't allow access to our app!"
end

  def destroy
  session[:user_id] = nil
  render :text => "You've logged out!"
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def omniauth_failure
		redirect_to auth_failure_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenditures/edit.html.erb
<h1>Edit your expenditure below:</h1>

<%= form_for @expenditure, :html => { :multipart => true } do |form| %>

	<p>
		<%= form.label :item %><br>
		<%= form.text_field :item %>
	</p>

	<p>
		<%= form.label :price %><br>
		<%= form.text_field :price %><br>
	</p>

	<p>
		Image<br><br>
		<%= form.file_field :image %>
	</p>

	<p>
		<%= form.submit %>
	</p>

<% end %>

app/views/expenditures/index.html.erb
<% @expenditures.each do |ex| %>
	<p><%= ex.item %></p>
	<p><%= ex.price %></p>
	<p><%= image_tag ex.image %></p>
<% end %>

app/views/expenditures/new.html.erb
<h1>Add a new expenditure below:</h1>

<%= form_for @expenditure, :html => { :multipart => true } do |form| %>

	<p>
		<%= form.label :item %><br>
		<%= form.text_field :item %>
	</p>

	<p>
		<%= form.label :price %><br>
		<%= form.text_field :price %><br>
	</p>

	<p>
		Image<br><br>
		<%= form.file_field :image %>
	</p>

	<p>
		<%= form.submit %>
	</p>

<% end %>

app/views/expenditures/show.html.erb
<br>
<%= @expenditure.item %><br>
<%= @expenditure.price %><br>
<%= image_tag @expenditure.image.url(:large) %><br>

<%= link_to 'Back to All Expenditures', expenditures_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brubudget</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
	Logged in as <strong><%= current_user.email %></strong>
	<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
	<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
<% else %>
	<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
	<%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
<% end %>

<% if notice %>
	<p class="alert alert-success"><%= notice %></p>
<% end %>

<% if alert %>
	<p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>